# Generated by Django 2.2.7 on 2019-11-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('row1', models.CharField(max_length=150)),
                ('row2', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
