# Generated by Django 2.2.7 on 2019-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('pontos_turisticos', '0004_auto_20191113_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='reviews',
            field=models.ManyToManyField(to='avaliacoes.Review'),
        ),
    ]
