# Generated by Django 2.2.7 on 2019-11-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
        ('pontos_turisticos', '0005_turisticpoint_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='localization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacao.Localization'),
            preserve_default=False,
        ),
    ]
