# Generated by Django 2.2.7 on 2019-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0007_auto_20191113_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turisticpoint',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='comentarios.Comment'),
        ),
        migrations.AlterField(
            model_name='turisticpoint',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.Review'),
        ),
    ]
