# Generated by Django 2.2.7 on 2019-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontos_turisticos', '0009_auto_20191113_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
